# Generated by Django 5.1.3 on 2024-11-30 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invite_codes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='customuser_phone_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='customuser_referred_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activated_invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by', to='invite_codes.invitecode'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='invite_codes.invitecode'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['activated_invite_code'], name='customuser_phone_number_idx'),
        ),
    ]
