# Generated by Django 5.1.3 on 2024-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invite_codes', '0002_invitecode_invite_code_code_idx'),
        ('users', '0002_remove_customuser_customuser_phone_number_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='customuser_act_invite_code_idx',
            old_name='customuser_phone_number_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='customuser_phone_number_idx'),
        ),
    ]
