# Generated by Django 5.1.3 on 2024-12-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_phoneauth_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
