# Generated by Django 5.1.3 on 2024-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_phoneauth_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phoneauth',
            index=models.Index(fields=['phone_number', 'code'], name='phoneauth_phone_code_idx'),
        ),
    ]
